name: 'Check Coverage'
description: 'Used to check coverage data during build'
inputs:
  access-token:
    required: true
  project-url:
    required: true
  coverage-files:
    required: true
  environment:
    required: false # assumes prod, if not specified
runs:
  using: "composite"
  steps:
    - name: Download cs-coverage binary, unzip it and make it executable
      run: |
        curl -s -o "$(pwd)/cs-coverage.zip" https://downloads.codescene.io/enterprise/cli/cs-coverage-linux-amd64-latest.zip
        unzip -oq "$(pwd)/cs-coverage.zip"
        chmod +x "$(pwd)/cs-coverage"
      shell: bash
    - name: CodeScene Code Coverage Check
      run: |
        echo "Using environment: ${{ inputs.environment }}"
        ls -alR $(pwd)/coverage/
        $(pwd)/cs-coverage check \
          --verbose \
          --coverage-files "${{ inputs.coverage-files }}"
      env:
        STAGING_CS_PROJECT_URL: ${{ inputs.project-url }}
        STAGING_CS_ACCESS_TOKEN: ${{ inputs.access-token }}
        CS_PROJECT_URL: ${{ inputs.project-url }}
        CS_ACCESS_TOKEN: ${{ inputs.access-token }}
        CS_ENV: ${{ inputs.environment }}
      shell: bash